apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookings-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookings
  template:
    metadata:
      labels:
        app: bookings
    spec:
      containers:
        - name: bookings
          image: fikrim/demo-fleet-bookings:1.0.0-react
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: demo-fleet
            - name: MONGO_URI
              value: 'mongodb://bookings-mongo-srv:27017/bookings'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NODE_ENV
              value: prod
---
apiVersion: v1
kind: Service
metadata:
  name: bookings-srv
spec:
  selector:
    app: bookings
  ports:
    - name: bookings
      protocol: TCP
      port: 3000
      targetPort: 3000
