name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - 'auth/v1/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: cd auth/v1 && docker build -t fikrim/demo-fleet-auth-v1 .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push fikrim/demo-fleet-auth-v1
