name: tests-booking

on:
  pull_request:
    paths:
      - 'bookings/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd bookings/v1/ && npm install && npm run test:ci
