name: tests-bids

on:
  pull_request:
    paths:
      - 'bids/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd bids/v1/ && npm install && npm run test:ci
